### ISSUE TITLE
Zero balance account not working

### ISSUE THREAD

**Issue by vekexasia** [RiseVision/rise-wallet#3]
As a user who just opened an account that have zero txs I would like to be able to re-login with such passphrase

**Comment by sachinverma1** [comment]
hi,
i have created my own pool , now since last 3 days i am running my pool on 280 mh/s for litecoin. but one problem i am facing with my pool is the balance on my wallet is not updating. 

is there any solution so that balance can be update into my wallet?

1. the wallet is generated by blockchain .
2. wallet is completely synced .

now i am not able to get the solution for balance update

when i run command on putty  ./litecoin-cli getinfo

then also balance shows 0

its been 3 days now i am facing this issue.

kindly give some info regarding this issue.

Regards
sachin verma
